### ISSUE TITLE
Using Card Reader with an actual nfc tag / card

### ISSUE THREAD

**Issue by kokhoor** [googlesamples/android-CardReader#3]
Based on protocol implemented in this Card Reader sample, is it possible to encode a physical NFC card that complies with the protocol used in Card Reader? What NFC tag will work?

Thanks.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
